#ifndef	_HYBRID_MAP_H_
#define	_HYBRID_MAP_H_

#define SECTOR_SIZE			512			
#define SPARE_SIZE			16			
#define PAGE_SIZE			(SECTOR_SIZE+SPARE_SIZE)
#define SECTORS_PER_PAGE		1
#define PAGES_PER_BLOCK		5
#define BLOCK_SIZE			(PAGE_SIZE*PAGES_PER_BLOCK)
#define BLOCKS_PER_DEVICE		7
#define DATABLKS_PER_DEVICE	(BLOCKS_PER_DEVICE - 1)

#define DATAPAGES_PER_DEVICE	(DATABLKS_PER_DEVICE*PAGES_PER_BLOCK)	

#endif